# Default node pool for applications; on-demand instances
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: application-ondemand
spec:
  disruption:
    budgets:
      - nodes: "2" # Max 2 nodes consolidated at a time if nodes are empty
        reasons:
          - Empty
      - nodes: "1" # max 1 node consolidated at a time if underutilised or nodepool updated
        reasons:
          - Underutilized
          - Drifted
    consolidateAfter: 60s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        nodepool-group: application
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: application-class
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values:
            - "6"
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
            - large
            - xlarge
            - 2xlarge
            - 4xlarge
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      terminationGracePeriod: 24h0m0s
  weight: 20
