# Instead of the default system pool
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: core
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata: {}
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: core-class
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: eks.amazonaws.com/instance-family
          operator: In
          values: ["m7a", "m7g"]
        - key: eks.amazonaws.com/instance-cpu
          operator: In
          values: ["1", "2"]
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      taints:
        - effect: NoSchedule
          key: CriticalAddonsOnly
      terminationGracePeriod: 24h0m0s
